---
- name: Ensure rsyslog is installed
  ansible.builtin.package:
    name: rsyslog
    state: present
  tags:
    - rsyslog_client
    - logging
    - packages

- name: Ensure rsyslog.d directory exists
  ansible.builtin.file:
    path: /etc/rsyslog.d
    state: directory
    mode: '0755'
  tags:
    - rsyslog_client
    - logging
    - config

- name: Configure rsyslog to forward logs to openobserve
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.d/99-openobserve.conf
    line: "*.* @{{ hostvars[groups['all'] | select('search', 'openobserve') | list | first]['ansible_host'] }}:5514"
    create: yes
  tags:
    - rsyslog_client
    - logging
    - config

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  tags:
    - rsyslog_client
    - logging
    - service
