---
- name: Ensure rsyslog is installed
  apt:
    name: rsyslog
    state: present
    update_cache: yes

- name: Configure rsyslog to forward logs to openobserve
  lineinfile:
    path: /etc/rsyslog.d/99-openobserve.conf
    line: "*.* @{{ hostvars[groups['all'] | select('search', 'openobserve') | list | first]['ansible_host'] }}:5514"
    create: yes

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
