---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true


- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart adguardhome
  ansible.builtin.systemd:
    name: adguardhome
    state: restarted
