services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=2001
      - PGID=988
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /docker/plex:/data
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=2002
      - PGID=988
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /docker/plex:/data
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=2004
      - PGID=988
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /docker/plex/media:/data/media
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 9696:9696
    environment:
      - PUID=2005
      - PGID=988
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config
  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8181:8181
    environment:
      - PUID=2006
      - PGID=988
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/tautulli:/config
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: >-
      tunnel --no-autoupdate run --token
      ${CLOUDFLARED_TUNNEL_TOKEN}
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr:latest
    restart: unless-stopped
    ports:
      - "8787:8787"
    environment:
      - PUID=2007
      - PGID=988
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/readarr:/config
      - /docker/plex:/data
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    restart: unless-stopped
    ports:
      - "8686:8686"
    environment:
      - PUID=2008
      - PGID=988
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/lidarr:/config
      - /docker/plex:/data
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - "8080:8080"
    environment:
      - PUID=2003
      - PGID=988
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sabnzbd:/config
      - /docker/plex/usenet:/data/usenet:rw
  plex-meta-manager:
    container_name: plex-meta-manager
    image: meisnate12/plex-meta-manager:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=988
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/plex-meta-manager:/config:rw
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    logging:
      driver: json-file
    depends_on:
      - ombi-mariadb
    environment:
      - PUID=1000
      - PGID=988
      - TZ=America/Chicago
    volumes:
      - /docker/appdata/ombi:/config
    ports:
      - 3579:3579
  ombi-mariadb:
    image: mariadb:latest
    container_name: ombi-mariadb
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - "MARIADB_USER=ombi"
      - "MARIADB_PASSWORD=ombi"
      - "MARIADB_DATABASE=ombi"
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - TZ=America/Chicago
    volumes:
      - "/docker/appdata/ombi-mariadb:/var/lib/mysql"
    ports:
      - 3306:3306
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:latest
    container_name: kiwix
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8090:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/kiwix:/data
    command:
      - '*.zim'
  boinc:
    image: lscr.io/linuxserver/boinc:latest
    container_name: boinc
    runtime: nvidia
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7080:8080
      - 7081:8081
      - 31416:31416
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PUID=1000
      - PGID=988
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/boinc:/config
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/appdata/portainer:/data
