apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: postgres, namespace: ${NS}}
spec: {accessModes: [ReadWriteOnce], resources: {requests: {storage: 5Gi}}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: backups, namespace: ${NS}}
spec: {accessModes: [ReadWriteOnce], resources: {requests: {storage: 2Gi}}}
