apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata: {name: authentik, namespace: ${NS}}
spec:
  hostAPI: ${HOST_API}
  authentication:
    universalAuth:
      credentialsRef: {secretName: infisical-universal-auth, secretNamespace: infisical-operator}
      secretsScope: {projectId: "${PROJECT_ID}", envSlug: prod, secretsPath: /${FOLDER}}
  managedKubeSecretReferences:
    - secretName: authentik-secrets
      secretNamespace: ${NS}
      template:
        data:
          AUTHENTIK_SECRET_KEY: "{{ .secret_key.Value }}"
          AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .postgres_password.Value }}"
          POSTGRES_PASSWORD: "{{ .postgres_password.Value }}"
          AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .bootstrap_password.Value }}"
          AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .bootstrap_token.Value }}"
          GRAFANA_OIDC_CLIENT_SECRET: "{{ .grafana_oidc_client_secret.Value }}"
          PORTAINER_OIDC_CLIENT_SECRET: "{{ .portainer_oidc_client_secret.Value }}"
          MESHCENTRAL_OIDC_CLIENT_SECRET: "{{ .meshcentral_oidc_client_secret.Value }}"
          PDM_OIDC_CLIENT_SECRET: "{{ .pdm_oidc_client_secret.Value }}"
          PVE_OIDC_CLIENT_SECRET: "{{ .pve_oidc_client_secret.Value }}"
          PBS_OIDC_CLIENT_SECRET: "{{ .pbs_oidc_client_secret.Value }}"
