apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata: {name: authentik, namespace: ${NS}}
spec:
  hostAPI: ${HOST_API}
  authentication:
    universalAuth:
      credentialsRef: {secretName: infisical-universal-auth, secretNamespace: infisical-operator}
      secretsScope: {projectId: "${PROJECT_ID}", envSlug: prod, secretsPath: /${FOLDER}}
  managedKubeSecretReferences:
    - secretName: authentik-secrets
      secretNamespace: ${NS}
      template:
        data:
          AUTHENTIK_SECRET_KEY: "{{ .secret_key.Value }}"
          AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .postgres_password.Value }}"
          POSTGRES_PASSWORD: "{{ .postgres_password.Value }}"
          AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .bootstrap_password.Value }}"
          AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .bootstrap_token.Value }}"
          LDAP_BIND_PASSWORD: "{{ .ldap_bind_password.Value }}"
