---

- name: Restart UniFi OS Server
  ansible.builtin.systemd:
    name: uosserver
    state: restarted

- name: Reload UFW
  community.general.ufw:
    state: reloaded

- name: Install UniFi certificate # noqa: command-instead-of-shell
  ansible.builtin.shell: "{{ unifi_cert_install }}"
  changed_when: true
