apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata: {name: traefik, namespace: traefik}
spec: {interval: 12h, url: https://traefik.github.io/charts}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: {name: traefik, namespace: traefik}
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "41.5.0"
      sourceRef: {kind: HelmRepository, name: traefik}
  install: {crds: CreateReplace}
  upgrade: {crds: CreateReplace}
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    image:
      registry: ${REGISTRY}/docker.io
    deployment:
      replicas: 1
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-tls
    service:
      annotations:
        metallb.io/loadBalancerIPs: ${INGRESS_IP}
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
      kubernetesCRD:
        allowCrossNamespace: true
