---
- name: Restart github-runner
  ansible.builtin.systemd:
    name: "actions.runner.{{ github_runner_repo | replace('/', '-') }}.{{ github_runner_name }}.service"
    state: restarted
    daemon_reload: true
