---
# Tasks for Multicast Relay VM
- name: Ensure required packages are installed
  apt:
    name:
      - git
      - python3
      - python3-netifaces
    state: present
    update_cache: yes
  tags:
    - multicast_relay
    - packages

- name: Clone multicast-relay repository
  git:
    repo: https://github.com/alsmith/multicast-relay.git
    dest: /bin/multicast-relay
    force: yes
  tags:
    - multicast_relay
    - install

- name: Copy ifFilter.json from inventory host_vars (or adjust as needed)
  copy:
    src: ../../terraform/services/ifFilter.json
    dest: /bin/multicast-relay/ifFilter.json
    owner: root
    group: root
    mode: '0644'
  tags:
    - multicast_relay
    - config

- name: Configure logrotate for multicast-relay
  copy:
    dest: /etc/logrotate.d/multicast-relay
    content: |
      /var/log/multicast-relay.log {
         compress
         daily
         missingok
         postrotate
            systemctl restart multicast-relay
          endscript
         rotate 7
      }
  tags:
    - multicast_relay
    - config
    - logging

- name: Create systemd service for multicast-relay
  copy:
    dest: /etc/systemd/system/multicast-relay.service
    content: |
      [Unit]
      Description=Multicast Relay
      Wants=network.target
      After=syslog.target network-online.target

      [Service]
      Restart=on-failure
      RestartSec=10
      User=root
      WorkingDirectory=/bin/multicast-relay
      ExecStart=python3 /bin/multicast-relay/multicast-relay.py --ifFilter /bin/multicast-relay/ifFilter.json --relay 255.255.255.255:7878 --interfaces eth_vlan100 eth_vlan120 eth_vlan121 eth_vlan130 --logfile /var/log/multicast-relay.log --verbose --foreground
      KillSignal=SIGINT

      [Install]
      WantedBy=multi-user.target
  tags:
    - multicast_relay
    - config
    - service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  tags:
    - multicast_relay
    - service

- name: Start and enable multicast-relay service
  systemd:
    name: multicast-relay
    state: started
    enabled: yes
  tags:
    - multicast_relay
    - service
