apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata: {name: metallb, namespace: metallb-system}
spec: {interval: 12h, url: https://metallb.github.io/metallb}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: {name: metallb, namespace: metallb-system}
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.16.1"
      sourceRef: {kind: HelmRepository, name: metallb}
  install: {crds: CreateReplace}
  upgrade: {crds: CreateReplace}
  values:
    frrk8s:
      enabled: false
    speaker:
      frr:
        enabled: false
      ignoreExcludeLB: true
