apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata: {name: vlan40, namespace: metallb-system}
spec:
  addresses: ["${POOL_START}-${POOL_END}"]
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata: {name: vlan40, namespace: metallb-system}
spec:
  ipAddressPools: [vlan40]
