apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [pvc.yaml, certificate.yaml, secrets.yaml, app.yaml, ../pg-backup]
configMapGenerator:
  - name: postgres-hba
    namespace: codeintel
    files: [pg_hba.conf]
