---
# Tasks for Homebridge VM
- name: Check if Homebridge repo is present
  ansible.builtin.shell: |
    grep -q 'repo.homebridge.io' /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null
  register: homebridge_repo_present
  changed_when: false
  failed_when: false
  tags:
    - homebridge
    - packages

- name: Add Homebridge repository
  ansible.builtin.deb822_repository:
    name: homebridge
    types: [deb]
    uris: "https://repo.homebridge.io"
    signed_by: "https://repo.homebridge.io/KEY.gpg"
    suites: stable
    components: [main]
    state: present
    enabled: yes
  when: homebridge_repo_present.rc != 0
  tags:
    - homebridge
    - packages

- name: Update apt cache
  apt:
    update_cache: yes
  tags:
    - homebridge
    - packages

- name: Install/Update Node.js LTS
  apt:
    name:
      - nodejs
      - npm
    state: latest
  tags:
    - homebridge
    - packages
    - nodejs

- name: Install Homebridge
  apt:
    name: homebridge
    state: present
  tags:
    - homebridge
    - packages

- name: Update Homebridge to latest version
  apt:
    name: homebridge
    state: latest
  tags:
    - homebridge
    - update
    - packages

- name: Update all Homebridge plugins
  community.general.npm:
    name: "*"
    global: yes
    state: latest
  become: true
  tags:
    - homebridge
    - update
    - plugins
  register: plugin_update
  changed_when: "'up to date' not in plugin_update.stdout"

- name: Restart Homebridge service after updates
  ansible.builtin.systemd:
    name: homebridge
    state: restarted
  when: plugin_update.changed
  tags:
    - homebridge
    - update
    - service
