---
- name: Manage Docker containers on the docker VM
  hosts: docker
  become: true

  vars_files:
    - ../group_vars/all.yml
  pre_tasks:
    - name: Load all configuration and secrets
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/full_pre_tasks.yml"
  roles:
    - docker
    - authentik
