---
- name: Configure nvidia-licensing VM
  hosts: nvidia-licensing
  become: yes
  vars_files:
    - ../group_vars/all.yml
  roles:
    - dns_config
    - nvidia_licensing
    - rsyslog_client
    - telegraf

- name: Configure homebridge VM
  hosts: homebridge
  become: yes
  vars_files:
    - ../group_vars/all.yml
  roles:
    - dns_config
    - homebridge
    - rsyslog_client
    - telegraf

- name: Configure multicast-relay VM
  hosts: multicast-relay
  become: yes
  vars_files:
    - ../group_vars/all.yml
  roles:
    - dns_config
    - multicast_relay
    - rsyslog_client
    - telegraf

- name: Configure docker VM
  hosts: docker
  become: yes
  vars_files:
    - ../group_vars/all.yml
  roles:
    - dns_config
    - docker
    - rsyslog_client
    - telegraf

- name: Configure plex VM
  hosts: plex
  become: yes
  vars_files:
    - ../group_vars/all.yml
  roles:
    - dns_config
    - plex
    - rsyslog_client
    - telegraf
