---
- name: Update DNS resolver configuration on all VMs
  hosts: all:!dns
  become: true
  vars_files:
    - ../group_vars/all.yml
  pre_tasks:
    - name: Load all configuration and secrets
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/full_pre_tasks.yml"
      tags: [always]
  roles:
    - dns_config
