---
- name: Update all VMs and Proxmox server
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache and upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes

- name: Update all Docker containers (pull latest and recreate)
  hosts: docker
  become: yes
  tasks:
    - name: Pull latest images for all running containers
      shell: |
        images=$(docker ps --format '{{'{{.Image}}'}}' | sort -u)
        if [ -n "$images" ]; then
          for img in $images; do
            docker pull "$img"
          done
        fi
      register: docker_pull_result
      changed_when: false

    - name: Restart all running containers with latest image
      shell: |
        containers=$(docker ps --format '{{'{{.Names}}'}}')
        if [ -n "$containers" ]; then
          docker restart $containers
        fi
      register: docker_restart_result
      changed_when: false

    - name: Prune unused Docker images
      shell: docker image prune -af
      register: docker_prune_result
      changed_when: false
