---
- name: Set IPv4 DNS server for each interface using resolvectl
  loop: "{{ dns_zones | dict2items }}"
  loop_control:
    loop_var: vlan
  ansible.builtin.command: >
    resolvectl dns eth_{{ vlan.key }} {{ vlan.value.dns_ip }}
  become: true
  changed_when: false
  when: "'eth_' + vlan.key in ansible_facts.interfaces"
  tags:
    - dns_config
    - dns
    - config

- name: Set IPv6 DNS server for each interface using resolvectl
  loop: "{{ dns_zones | dict2items }}"
  loop_control:
    loop_var: vlan
  ansible.builtin.command: >
    resolvectl dns eth_{{ vlan.key }} {{ vlan.value.dns_ip }} {{ vlan.value.dns_ipv6 }}
  become: true
  changed_when: false
  when:
    - "'eth_' + vlan.key in ansible_facts.interfaces"
    - vlan.value.dns_ipv6 is defined
    - vlan.value.dns_ipv6 | length > 0
  tags:
    - dns_config
    - dns
    - config

- name: Wait for apt lock to be released
  ansible.builtin.shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done
  changed_when: false
  timeout: 300
  tags:
    - dns_config
    - packages

- name: Ensure dnsutils is installed
  ansible.builtin.apt:
    name:
      - dnsutils
    state: present
    update_cache: true

  retries: 3
  delay: 10
  register: apt_result
  until: apt_result is success
  tags:
    - dns_config
    - dns
    - packages

- name: Set DNS search suffix for each interface by VLAN
  loop: "{{ dns_zones | dict2items }}"
  loop_control:
    loop_var: vlan
  ansible.builtin.command: >
    resolvectl domain eth_{{ vlan.key }} {{ vlan.value.zone }}
  become: true
  changed_when: false
  when: "'eth_' + vlan.key in ansible_facts.interfaces"
  tags:
    - dns_config
    - dns
    - config
