---
- name: Install iptables and iptables-persistent
  apt:
    name:
      - iptables
      - iptables-persistent
    state: present
    update_cache: yes

- name: Set default iptables policies to DROP
  iptables:
    chain: "{{ item }}"
    policy: DROP
    table: filter
  loop:
    - INPUT
    - FORWARD
    - OUTPUT

- name: Allow established and related connections
  iptables:
    chain: INPUT
    protocol: all
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow loopback traffic
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Allow SSH
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

# Add additional rules for required services (DNS, Docker, Plex, etc.) as needed

- name: Save iptables rules
  command: iptables-save > /etc/iptables/rules.v4

- name: Ensure SELinux is installed (Debian/Ubuntu - install selinux-basics)
  apt:
    name: selinux-basics
    state: present
    update_cache: yes

- name: Enable SELinux (permissive mode for compatibility)
  command: selinux-activate
  args:
    creates: /etc/selinux/selinux.conf
  ignore_errors: yes

- name: Set SELinux to permissive mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
  when: ansible_facts['os_family'] == 'Debian'

- name: Reboot if SELinux was just enabled
  reboot:
    msg: "Rebooting to apply SELinux changes."
  when:
    - ansible_facts['os_family'] == 'Debian'
    - ansible_facts['selinux']['status'] != 'enabled'
    - ansible_facts['selinux']['mode'] != 'permissive'
  ignore_errors: yes
