#!/usr/bin/env python3
from __future__ import annotations

import argparse
import pathlib
import re


DEPRECATED_VARS = [
    "openobserve_root_user_pass",
    "grafana_admin_password",
    "proxmox_token_value",
    "unifi_admin_password",
    "unifi_password",
    "synology_admin_password",
    "cloudflared_tunnel_token",
    "pbs_admin_password",
    "pbs_backup_user_password",
    "pbs_backup_token",
    "pbs_api_token",
    "pbs_monitoring_token",
    "postgres_password",
    "plex_smb_pass",
]

INCLUDE_SUFFIXES = {".yml", ".yaml", ".j2", ".py", ".md", ".tf", ".sh"}
EXCLUDE_PARTS = {".git", ".venv", "node_modules", "terraform/.terraform", "Library"}


def should_skip(path: pathlib.Path) -> bool:
    text = path.as_posix()
    return any(part in text for part in EXCLUDE_PARTS)


def collect_files(root: pathlib.Path) -> list[pathlib.Path]:
    files: list[pathlib.Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if should_skip(path):
            continue
        if path.suffix.lower() not in INCLUDE_SUFFIXES:
            continue
        files.append(path)
    return files


def scan_var(file_path: pathlib.Path, var_name: str) -> list[tuple[int, str]]:
    pattern = re.compile(rf"\b{re.escape(var_name)}\b")
    findings: list[tuple[int, str]] = []
    lines = file_path.read_text(encoding="utf-8", errors="ignore").splitlines()
    for line_no, line in enumerate(lines, start=1):
        if pattern.search(line):
            findings.append((line_no, line.strip()))
    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit deprecated variable references for PR8 cleanup")
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument(
        "--output",
        default="docs/pr8-deprecated-var-audit.md",
        help="Audit report output markdown path",
    )
    args = parser.parse_args()

    root = pathlib.Path(args.root).resolve()
    output = pathlib.Path(args.output).resolve()

    files = collect_files(root)
    report_lines: list[str] = []
    report_lines.append("# PR8 Deprecated Variable Audit")
    report_lines.append("")
    report_lines.append("This report is generated by `scripts/audit_deprecated_vars.py`.")
    report_lines.append("")

    total_findings = 0
    for var_name in DEPRECATED_VARS:
        var_findings: list[tuple[pathlib.Path, int, str]] = []
        for file_path in files:
            if file_path == output:
                continue
            matches = scan_var(file_path, var_name)
            for line_no, line_text in matches:
                rel = file_path.relative_to(root)
                var_findings.append((rel, line_no, line_text))

        report_lines.append(f"## `{var_name}`")
        report_lines.append("")
        if not var_findings:
            report_lines.append("- No references found.")
            report_lines.append("")
            continue

        total_findings += len(var_findings)
        report_lines.append(f"- References: {len(var_findings)}")
        report_lines.append("")
        for rel, line_no, line_text in var_findings:
            report_lines.append(f"- {rel}:{line_no} -> {line_text}")
        report_lines.append("")

    report_lines.append(f"Total findings: {total_findings}")
    report_lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(report_lines), encoding="utf-8")
    print(f"Wrote audit report: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
