---
# Tasks for DNS VM (Bind9)
- name: Ensure required packages are installed
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-dnsutils
    state: present
    update_cache: yes

- name: Gather all interface IPs (except loopback)
  set_fact:
    dns_listen_ips: "{{ ansible_all_ipv4_addresses | difference(['127.0.0.1']) }}"

- name: Configure named.conf.options to listen on all DNS VM IPs
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Ensure bind9 is started and enabled
  systemd:
    name: bind9
    state: started
    enabled: yes

- name: Deploy VLAN-specific zone files
  loop: "{{ dns_zones | dict2items }}"
  loop_control:
    loop_var: vlan_zone
  template:
    src: db.zone.j2
    dest: "/var/lib/bind/db.{{ vlan_zone.value.zone }}"
    mode: '0644'
    owner: bind
    group: bind
  vars:
    zone_name: "{{ vlan_zone.value.zone }}"
    zone_dns_ip: "{{ vlan_zone.value.dns_ip }}"
  notify: Restart bind9

- name: Ensure VLAN zones are configured in named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    mode: '0644'
    owner: root
    group: bind
  notify: Restart bind9
