---
# Tasks for DNS VM (Bind9)
- name: Ensure required packages are installed
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-dnsutils
    state: present
    update_cache: yes

- name: Gather all interface IPs (except loopback)
  set_fact:
    dns_listen_ips: "{{ ansible_all_ipv4_addresses | difference(['127.0.0.1']) }}"

- name: Configure named.conf.options to listen on all DNS VM IPs
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Ensure bind9 is started and enabled
  systemd:
    name: bind9
    state: started
    enabled: yes

- name: Deploy goodolclint.cloud zone file
  template:
    src: db.goodolclint.cloud.j2
    dest: /etc/bind/db.goodolclint.cloud
    mode: '0644'
  notify: Restart bind9

- name: Ensure goodolclint.cloud zone is configured in named.conf.local
  blockinfile:
    path: /etc/bind/named.conf.local
    marker: "// ANSIBLE MANAGED ZONE BLOCK {mark} goodolclint.cloud"
    block: |
      zone "goodolclint.cloud" {
        type master;
        file "/etc/bind/db.goodolclint.cloud";
      };
  notify: Restart bind9
