---
- name: Install NVIDIA GRID driver
  import_role:
    name: nvidia
  tags:
    - plex
    - nvidia
    - driver

- name: Ensure required packages.
  ansible.builtin.package:
    name:
      - nfs-common
      - cifs-utils
    state: present
  tags:
    - plex
    - packages

- name: Ensure NFS fstab entry and mount.
  ansible.posix.mount:
    backup: yes
    boot: "yes"
    path: "/mnt/plex"
    src: "{{ plex_nfs_src }}"
    fstype: nfs
    opts: "defaults"
    state: "mounted"
  tags:
    - plex
    - storage
    - nfs

- name: Mount /mnt/media
  file:
    src: /mnt/plex/data/media
    dest: /mnt/media
    state: link
  tags:
    - plex
    - storage

- name: Check if Plex GPG key exists
  stat:
    path: /usr/share/keyrings/plex.gpg
  register: plex_gpg_key
  tags:
    - plex
    - packages

- name: Download Plex APT GPG key to temp file
  ansible.builtin.get_url:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    dest: /tmp/plex.gpg.key
    mode: '0644'
  when: not plex_gpg_key.stat.exists
  tags:
    - plex
    - packages

- name: Convert Plex GPG key to dearmored format
  ansible.builtin.command:
    cmd: gpg --batch --dearmor -o /usr/share/keyrings/plex.gpg /tmp/plex.gpg.key
  args:
    creates: /usr/share/keyrings/plex.gpg
  when: not plex_gpg_key.stat.exists
  tags:
    - plex
    - packages

- name: Check if Plex APT repo is present
  ansible.builtin.shell: grep -q '^deb .*/plex' /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null
  register: plex_repo_present
  changed_when: false
  failed_when: false
  tags:
    - plex
    - packages

- name: Add Plex official APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/plex.gpg] https://downloads.plex.tv/repo/deb public main"
    state: present
    filename: plexmediaserver
  when: plex_repo_present.rc != 0
  tags:
    - plex
    - packages

- name: Check if Plex is installed
  ansible.builtin.stat:
    path: /usr/lib/plexmediaserver
  register: plex_installed
  tags:
    - plex
    - packages

- name: Install latest Plex Media Server
  ansible.builtin.apt:
    name: plexmediaserver
    state: latest
    update_cache: yes
  when: not plex_installed.stat.exists
  tags:
    - plex
    - packages

- name: Create PBS backup script for Plex config
  ansible.builtin.template:
    dest: /usr/local/bin/plex_config_pbs_backup.sh
    mode: '0755'
    owner: root
    group: root
    src: plex_config_pbs_backup.sh.j2
  when: pbs_backup_enabled | default(true)
  tags:
    - plex
    - backup
    - pbs

- name: Create PBS restore script for Plex config
  ansible.builtin.template:
    dest: /usr/local/bin/plex_config_pbs_restore.sh
    mode: '0755'
    owner: root
    group: root
    src: plex_config_pbs_restore.sh.j2
  when: pbs_backup_enabled | default(true)
  tags:
    - plex
    - backup
    - pbs

- name: Create SMB backup script for Plex config (fallback)
  ansible.builtin.template:
    dest: /usr/local/bin/plex_config_backup.sh
    mode: '0755'
    owner: root
    group: root
    src: plex_config_backup.sh.j2
  when: not (pbs_backup_enabled | default(true))
  tags:
    - plex
    - backup
    - smb

- name: Create SMB restore script for Plex config (fallback)
  ansible.builtin.template:
    dest: /usr/local/bin/plex_config_restore.sh
    mode: '0755'
    owner: root
    group: root
    src: plex_config_restore.sh.j2
  when: not (pbs_backup_enabled | default(true))
  tags:
    - plex
    - backup
    - smb

- name: Ensure cron job for nightly Plex config PBS backup
  ansible.builtin.cron:
    name: "Nightly Plex config PBS backup"
    user: root
    job: "/usr/local/bin/plex_config_pbs_backup.sh"
    minute: 0
    hour: 2
    state: present
  when: pbs_backup_enabled | default(true)
  tags:
    - plex
    - backup
    - pbs
    - cron

- name: Remove old SMB backup cron job when PBS is enabled
  ansible.builtin.cron:
    name: "Nightly Plex config backup"
    state: absent
  when: pbs_backup_enabled | default(true)
  tags:
    - plex
    - backup
    - cron

- name: Ensure cron job for nightly Plex config SMB backup (fallback)
  ansible.builtin.cron:
    name: "Nightly Plex config backup"
    user: root
    job: "/usr/local/bin/plex_config_backup.sh"
    minute: 0
    hour: 2
    state: present
  when: not (pbs_backup_enabled | default(true))
  tags:
    - plex
    - backup
    - smb
    - cron

- name: Restore Plex config from PBS if not already installed
  ansible.builtin.shell: /usr/local/bin/plex_config_pbs_restore.sh
  when: 
    - not plex_installed.stat.exists
    - pbs_backup_enabled | default(true)
  args:
    executable: /bin/bash
  tags:
    - plex
    - backup
    - pbs
    - restore

- name: Restore Plex config from SMB if not already installed (fallback)
  ansible.builtin.shell: /usr/local/bin/plex_config_restore.sh
  when: 
    - not plex_installed.stat.exists
    - not (pbs_backup_enabled | default(true))
  args:
    executable: /bin/bash
  tags:
    - plex
    - backup
    - smb
    - restore
