---
- name: Restart Docker daemon
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  listen: restart docker

- name: restart plex services docker compose
  community.docker.docker_compose_v2:
    project_src: /opt/plex-services
    state: restarted
  listen: "restart plex services docker compose"
