apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: metallb, namespace: flux-system}
spec:
  interval: 10m
  path: ./kubernetes/metallb
  prune: false
  sourceRef: {kind: GitRepository, name: homelab}
  serviceAccountName: flux-metallb
  postBuild:
    substituteFrom: [{kind: ConfigMap, name: cluster-bindings}]
