apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: traefik, namespace: flux-system}
spec:
  interval: 10m
  path: ./kubernetes/traefik
  prune: false
  sourceRef: {kind: GitRepository, name: homelab}
  serviceAccountName: flux-traefik
  postBuild:
    substituteFrom: [{kind: ConfigMap, name: cluster-bindings}]
